#!/bin/bash
exec jupyter lab --ip 0.0.0.0 --port 8888 --AiExtension.default_language_model=openai-chat:gpt-4

#exec jupyter lab --ip 0.0.0.0 --port 8888 --AiExtension.default_language_model=openai-chat:gpt-4
#echo 'This is a test'


# Create the target directory if it doesn't exist
#mkdir -p ~/.local/share/jupyter/jupyter_ai

# Copy the config.json file to the target directory
#cp binder/config.json ~/.local/share/jupyter/jupyter_ai/config.json
#cp binder/config_schema.json ~/.local/share/jupyter/jupyter_ai/config_schema.json

#echo 'start file successfully used'

#exec "$@"
